apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: helm-monitoring
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-03-09T13:53:51Z"
  labels:
    app: kube-prometheus-stack-kube-proxy
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 30.0.1
    chart: kube-prometheus-stack-30.0.1
    heritage: Helm
    jobLabel: kube-proxy
    release: stable
  name: stable-kube-prometheus-sta-kube-proxy
  namespace: kube-system
  resourceVersion: "13829602"
  uid: 13008718-192d-4b47-9f5a-88bf60516e69
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    k8s-app: kube-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
