apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      
      - job_name: 'kubernetes-apiservers'

        kubernetes_sd_configs:
        - role: endpoints
        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics     
      
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
      
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      - job_name: 'kubernetes-cadvisor'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
        - role: endpoints

        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
      
      - job_name: 'kubernetes-etcd'
        scheme: https
        tls_config:
          insecure_skip_verify: true
          cert_file: /etc/prometheus/secrets/client.pem
          key_file: /etc/prometheus/secrets/client-key.pem
        static_configs:
          - targets: ['192.168.32.10:2379','192.168.32.20:2379','192.168.32.30:2379']

            #      - job_name: kube-prometheus-kubelet
            #        honor_labels: true
            #        kubernetes_sd_configs:
            #        - role: endpoints
            #          namespaces:
            #            names:
            #            - kube-system
            #        scheme: https
            #        tls_config:
            #          insecure_skip_verify: true
            #          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            #        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            #        relabel_configs:
            #        - source_labels:
            #          - job
            #          target_label: __tmp_prometheus_job_name
            #        - action: keep
            #          source_labels:
            #          - __meta_kubernetes_service_label_app_kubernetes_io_name
            #          - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            #          regex: (kubelet);true
            #        - action: keep
            #          source_labels:
            #          - __meta_kubernetes_service_label_k8s_app
            #          - __meta_kubernetes_service_labelpresent_k8s_app
            #          regex: (kubelet);true
            #        - action: keep
            #          source_labels:
            #          - __meta_kubernetes_endpoint_port_name
            #          regex: https-metrics
            #        - source_labels:
            #          - __meta_kubernetes_endpoint_address_target_kind
            #          - __meta_kubernetes_endpoint_address_target_name
            #          separator: ;
            #          regex: Node;(.*)
            #          replacement: ${1}
            #          target_label: node
            #        - source_labels:
            #          - __meta_kubernetes_endpoint_address_target_kind
            #          - __meta_kubernetes_endpoint_address_target_name
            #          separator: ;
            #          regex: Pod;(.*)
            #          replacement: ${1}
            #          target_label: pod
            #        - source_labels:
            #          - __meta_kubernetes_namespace
            #          target_label: namespace
            #        - source_labels:
            #          - __meta_kubernetes_service_name
            #          target_label: service
            #        - source_labels:
            #          - __meta_kubernetes_pod_name
            #          target_label: pod
            #        - source_labels:
            #          - __meta_kubernetes_pod_container_name
            #          target_label: container
            #        - source_labels:
            #          - __meta_kubernetes_service_name
            #          target_label: job
            #          replacement: ${1}
            #        - source_labels:
            #          - __meta_kubernetes_service_label_k8s_app
            #          target_label: job
            #          regex: (.+)
            #          replacement: ${1}
            #        - target_label: endpoint
            #          replacement: https-metrics
            #        - source_labels:
            #          - __metrics_path__
            #          target_label: metrics_path
            #        - source_labels:
            #          - __address__
            #          target_label: __tmp_hash
            #          modulus: 1
            #          action: hashmod
            #        - source_labels:
            #          - __tmp_hash
            #          regex: 0
            #          action: keep
            #        metric_relabel_configs: []
            #      
