apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-all-namespace
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/description: >-
      allow connection between pods in same namesapce      
spec:
  rules:
  - name: default-deny
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: NetworkPolicy
      name: allow-same-namespace
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          podSelector:
            matchLabels:
          ingress:
          - from:
            - podSelector: {}
